name: CMake + CTest

on:
  push:
    branches: [ main, week2/** ]
  pull_request:
    branches: [ main, week2/** ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Install Ninja
    - name: Install Ninja
      if: runner.os == 'Windows'
      uses: seanmiddleditch/gha-setup-ninja@v3

    # Configure & build
    - name: Configure CMake
      run: cmake -S week 2/project-calc -B build -DCMAKE_BUILD_TYPE=Debug -G Ninja

    - name: Build
      run: cmake --build build --config Debug --parallel

    # Run tests
    - name: Run tests
      run: ctest --test-dir build --output-on-failure
