name: CMake + CTest

on:
  push:
    branches:
      - main
      - 'week2/**'
  pull_request:
    branches:
      - main
      - 'week2/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ninja (Windows)
        if: runner.os == 'Windows'
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure CMake
        run: cmake -S "week 2/project-calc" -B build -DCMAKE_BUILD_TYPE=Debug -G Ninja

      - name: Build
        run: cmake --build build --config Debug --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
